package com.daniel.ping.domain.utilities

object Constants {

    const val KEY_PREFERENCE_NAME = "appPreference"
    const val KEY_IS_SIGNED_IN = "isSignedIn"
    const val KEY_IS_PROFILE_FULLY_COMPLETED = "isProfileFullyCompleted"
    const val KEY_COLLECTION_USERS = "users"
    const val KEY_STORAGE_IMAGES = "images"
    const val KEY_STORAGE_FILES = "files"
    const val KEY_NAME = "name"
    const val KEY_EMAIL = "email"
    const val KEY_USER_ID = "userId"
    const val KEY_DESCRIPTION = "description"
    const val KEY_IMAGE = "image"
    const val KEY_FCM_TOKEN = "fcmToken"
    const val KEY_COLLECTION_CHAT = "chats"
    const val KEY_TIMESTAMP = "timestamp"
    const val KEY_DATE_TIME = "dateTime"
    const val KEY_SENDER_ID = "senderId"
    const val KEY_RECEIVER_ID = "receiverId"
    const val KEY_COLLECTION_CONVERSATIONS = "recent_conversations"
    const val KEY_SENDER_FCM_TOKEN = "senderFcmToken"
    const val KEY_SENDER_DESCRIPTION = "senderDescription"
    const val KEY_RECEIVER_FCM_TOKEN = "receiverFcmToken"
    const val KEY_RECEIVER_DESCRIPTION = "receiverDescription"
    const val KEY_SENDER_NAME = "senderName"
    const val KEY_SENDER_IMAGE = "senderImage"
    const val KEY_RECEIVER_NAME = "receiverName"
    const val KEY_RECEIVER_IMAGE = "receiverImage"
    const val KEY_TYPE_MESSAGE = "typeMessage"
    const val KEY_IMAGE_URL = "imageUrl"
    const val KEY_FILE_URL = "fileUrl"
    const val KEY_MESSAGE = "message"
    const val KEY_AVAILABILITY = "availability"
    const val MESSAGE_TYPE_IMAGE = "image"
    const val MESSAGE_TYPE_TEXT = "text"
    const val MESSAGE_TYPE_FILE = "file"
    const val BASE_URL = "https://fcm.googleapis.com/"
    const val PATH_URL = "fcm/send"
    const val NOTIFICATION_ID = 120002
    const val CHANNEL_ID = "Channel"
}